### ISSUE TITLE
TotalCaputure_60FPS_Original 

### ISSUE THREAD

**Issue by whl-007** [jyf588/transformer-inertial-poser#10]
I don't know which dataset to download for TotalCapture_60FPS_Original in TC IMU signals preprocessed by dip's authors. Could you please point it out for me? I have already obtained the download permission from dip's authors.
![image](https://github.com/jyf588/transformer-inertial-poser/assets/120098257/65332ded-9bd9-44a2-bf02-4dfb0a114d27)
Could you please help me identify which datasets in the picture are related to TotalCaputure_60FPS_Original? The picture contains many datasets labelled as s1 to s5, but I couldn't find TotalCaputure_60FPS_Original in it.

**Comment by jyf588** [comment]
Make sure you have obtained permission from both DIP and TotalCapture authors. After that, you can send me your gmail account and I will share the file with you.

**Comment by whl-007** [comment]
Thank you very much，I have obtained permission from both DIP and TotalCapture authors. My gmail address is whl835643010@gmail.com

**Comment by whl-007** [comment]
Thank you very much，I have obtained permission from both DIP and TotalCapture authors. My email address is whl835643010@126.com

**Comment by jyf588** [comment]
Just shared the link. Let me know if it does not work.

**Comment by whl-007** [comment]
The link is https://dip.is.tue.mpg.de/download.php,you may not understand what I had said.I mean that I can not find the “TotalCaputure_60FPS_Original” dataset in dip's datasets under the picture.I only found one similar dataset called "TotalCapture_Real_60FPS.zip"，Can you help me out?
![image](https://github.com/jyf588/transformer-inertial-poser/assets/120098257/77d42b29-38f6-4dca-80ac-71d9c356d186)

**Comment by gzhGit** [comment]
> Make sure you have obtained permission from both DIP and TotalCapture authors. After that, you can send me your gmail account and I will share the file with you.

I encountered the same issue. Could you please share "TotalCapture_60FPS_Original" with me? I have obtained permission from both DIP and TotalCapture authors. My gmail account is [1042458519@qq.com](mailto:1042458519@qq.com). Thank you very much!
