### ISSUE TITLE
Aligning the coordinate systems of IMUs

### ISSUE THREAD

**Issue by whl-007** [jyf588/transformer-inertial-poser#11]
I would like to ask you about aligning the coordinate systems of different IMUs. Is it true that during motion capture experiments, you convert the acceleration and attitude angle information of all IMUs into the ENU coordinate system to align the coordinate systems of the six IMUs (processing everything in the ENU coordinate system)? I hope you can answer my question. Thank you very much!

**Comment by jyf588** [comment]
It’s a bit complex to explain here but the Appendix D of the paper contains a lot of details on this process. Feel free to let me know if anything in that section of the paper is confusing to you.

To briefly answer your question, we convert everything to a fixed global frame, but not necessarily ENU. I choose this global frame to be the room frame (check out the image of the IMUs in Readme, the lines of the carpet represent the room frame I used). During calibration pose, I always stand along those lines on the carpet. This room frame is up to a heading angle wrt ENU

**Comment by whl-007** [comment]
First of all, thank you very much for answering my question. I noticed something about calibration in Appendix D of your paper. You mentioned that you placed the sensor in a position consistent with the global coordinate system and obtained the initial orientation 𝑹 Gn Gp of the sensor in the global coordinate system. What exactly does the global coordinate system refer to? Additionally, I'm not quite sure how you aligned your multiple IMU sensors with the global coordinate system. Did you use any special precise methods? Would there be significant errors if I aligned them manually? I hope you can clarify these questions for me!
![image](https://github.com/jyf588/transformer-inertial-poser/assets/120098257/d6bb5774-f6b7-4465-9e9b-015dd67a485b)

**Comment by jyf588** [comment]
As I mentioned earlier, the global coordinate frame G_p is just the room frame, whose x and y axes point along the lines on the carpet of the room, and the z axis is simply up direction (https://github.com/jyf588/transformer-inertial-poser/blob/master/data/calib.jpg).

I didn't do anything special. Again, if you take a look at the jpeg photo, I simply put all IMU sensors so that they align exactly with the room frame (G_p). And from their readings in this pose you obtain the offsets R G_n G_p for each sensor.

**Comment by whl-007** [comment]
I understand now. Thank you for clarifying, and I apologize for my carelessness.
