### ISSUE TITLE
Query Regarding Model in Your Paper

### ISSUE THREAD

**Issue by Jaceyxy** [jyf588/transformer-inertial-poser#12]
Dear Author,
I've been testing your released model, model-without-dip9and10.pt, but found inconsistencies with the results from Table 1 of your paper.
Is the model used in Table 1 the same as the model-without-dip9and10.pt? If so, could you explain the reason for these discrepancies?
Looking forward to your guidance.
Best,
![image](https://github.com/jyf588/transformer-inertial-poser/assets/54926038/816fd3ed-fe97-4954-884e-ac0a1b8536a6)
![image](https://github.com/jyf588/transformer-inertial-poser/assets/54926038/ad6772f3-7969-42fe-96ac-ce5ea36983d7)
![image](https://github.com/jyf588/transformer-inertial-poser/assets/54926038/e5b482d7-af1f-4e38-9744-adca4ab41fa2)

**Comment by jyf588** [comment]
Please read the correct version of the paper: https://arxiv.org/pdf/2203.15720.pdf

**Comment by Jaceyxy** [comment]
Thanks very much!!!
