### ISSUE TITLE
Room frames（Gp）

### ISSUE THREAD

**Issue by whl-007** [jyf588/transformer-inertial-poser#14]
Hello, I have some questions that I would like to ask you:

1、May I know how you obtain the room coordinate system Gp?  I noticed that you have drawn some lines on the carpet based on your room coordinate system.  Is it calculated by measuring several positions using high-precision instruments and then determining the coordinate system for the entire plane?  After obtaining the room coordinate system Gp, do the starting positions for the 6 IMUs align parallel to this room coordinate system Gp by default?  Could you please let me know where in the code I can find the room coordinate system?  Also, is it possible to transform this room coordinate system Gp to the coordinate system calibrated by the optical motion capture device?  I would appreciate it if you could provide some guidance.
2、I would like to inquire about the content of the Rs_aligned_T_pose matrix.  I noticed that all 6 rows of data are the same.  Does this matrix represent the initial position setting for the 6 IMUs?  If so, why are they all the same，aren't they in different locations in body?  Furthermore, if I only want to use two IMUs, do I just need to consider two rows of data?
3、Regarding the IMU usage, do I need to place the IMU in a straight line on the ground every time?  Or after performing the calibration process, can the IMU be placed at the specified position on the body for subsequent uses?

**Comment by jyf588** [comment]
1. No. Those lines just come with the carpet. I just use those lines to make sure I will be facing the approximately same direction during the [3s T-pose calibration](https://github.com/jyf588/transformer-inertial-poser/blob/master/live_demo_new.py#L238) as during the sensor-on-floor [calibration (the photo in the Readme as you also referred to)](https://github.com/jyf588/transformer-inertial-poser/blob/master/live_demo_new.py#L217). So Gp is really arbitrary as long as it's aligned with gravity direction. e.g., if your room has tiles on the floor, feel free to use the seams between tiles.

2. They are the R_Gp_B0 in the paper Appendix [(code here)](https://github.com/jyf588/transformer-inertial-poser/blob/master/live_demo_new.py#L246). These mean the bone orientations not the IMU orientations. Note that the bone orientations is something SMPL defines: identity (zero) pose to be T-pose (https://files.is.tue.mpg.de/black/papers/SMPL2015.pdf)

3. It's better if you re-calibrate every few minutes (i.e. after each run). Technically though if you don't turn off the system you can take sensors off and put them back on to exact same locations, without re-calibration. But IMU drifting might degrade your quality.

**Comment by whl-007** [comment]
Thank you very much！
