### ISSUE TITLE
The problem about fairmotion: 'Motion' object has no attribute 'set_fps'

### ISSUE THREAD

**Issue by isshpan** [jyf588/transformer-inertial-poser#2]
Thanks for the nice work! I have some problems about the fairmotion. When I run the preprocess_DIP_TC_new.py, I will get the error:  'Motion' object has no attribute 'set_fps'. I install fairmotion by running 'pip install fairmotion'. So could you please help me solve this problem?

**Comment by isshpan** [comment]
It seems like the problem is the version of fairmotion.

**Comment by jyf588** [comment]
Are you following the instructions (https://github.com/jyf588/transformer-inertial-poser#environment-setup Step 6) and install fairmotion from my fork?

**Comment by isshpan** [comment]
When I follow this, I will get a tls error because of the git clone and git fetch command. But I have solved it by installing the dependency of fairmotion separately. Thanks for your comments too.
