### ISSUE TITLE
Effect of the SBP for joint motion correction

### ISSUE THREAD

**Issue by Wenchao-M** [jyf588/transformer-inertial-poser#3]
Hello, thanks for your excellent work! 

I tried to evaluate your model on the DanceDB and DIP IMU datasets. I use your pretrained model "model-without-dip9and10.pt" and the retrained one by myself. However, for both of these two models, I got better results when running test_run_ours_gpt_v4_with_c_rt_minimal(), which means only use the SBPs for root correction. For example, when I test your released checkpoint on the DanceDB dataset， I got
loss_angle: 14.596411590771083
loss_j_pos: 7.566159683066048
loss_2s_root: 0.022359336708061575
loss_5s_root: 0.09909819956046487
loss_10s_root: 0.28028876447285034
loss_jerk_max: 1.3138657493107144
loss_jerk_root: 0.8364943741098269
using test_run_ours_gpt_v4_with_c_rt_minimal(). 
But the results of the test_run_ours_gpt_v4_with_c_rt() is: 
loss_angle: 14.613705011926633
loss_j_pos: 7.568692342151206
loss_2s_root: 0.029894802392026975
loss_5s_root: 0.10650085406996405
loss_10s_root: 0.27479880557401726
loss_jerk_max: 1.408000152377208
loss_jerk_root: 0.9518027618990865,
this is in accord with the results reported in your paper.  But why the first one can get a better result, could you please help me figure it out?

**Comment by jyf588** [comment]
Hi! What you observe (similar performance for two versions) is expected! The additional features beyond the "minimal" version, as we mentioned in the README, are mainly for motions on uneven terrains, and long duration sitting motions. Since the test datasets don't really have these cases, both versions should expectedly perform very similarly.

**Comment by Wenchao-M** [comment]
> 
I got it. Thanks for your reply!
