### ISSUE TITLE
The definition of SMPL 18 joints

### ISSUE THREAD

**Issue by yukichou** [jyf588/transformer-inertial-poser#4]
Thanks for doing such great job.
The paper mentioned that the output will be18 joints angles defined in SMPL human model, but SMPL has 24 joints, so what's the difference between 18 and 24 joints? How can I use 18 joints to drive the normal SMPL model?

**Comment by jyf588** [comment]
Hello! There are six joints ignored — two toes, two wrists, and two palms (i.e. [“hand”](https://github.com/jyf588/transformer-inertial-poser/blob/master/constants.py#L56) per SMPL naming). One cannot reasonably estimate them from only 6 IMUs. Previous works also freeze them when using SMPL to visualize I believe.

I’m not sure about the coding details, but it shouldn’t be hard to swap the visualizer from PyBullet to SMPL. The main thing you need to figure out is the different ordering we use for the 18 SMPL joints. This joint ordering of our model’s output, unsurprisingly, is the same as the ordering during our data synthesis. So [this function](https://github.com/jyf588/transformer-inertial-poser/blob/master/data_utils.py#L103) can help you crack out the joint correspondence.

**Comment by yukichou** [comment]
I see. Thank you so much!

**Comment by syguan96** [comment]
Hi @jyf588 , Thanks for your great work and code! I have another related question. Hope you can help me.
Previous works (DIP, TransPose) not only ignore [10,11,20,21,22,23] but also ignore [7,8]. The joint index definition is shown below. What's your motivation to additionally predict the rotation of Joint 7,8?
![image](https://user-images.githubusercontent.com/81640539/228105299-83467d41-d418-4c1d-9fd7-9cbddba8ff69.png)

**Comment by jyf588** [comment]
Hi @syguan96, that's a good question. The decision was somewhat arbitrary -- in the beginning of this project we thought that ankle angles can be pretty much guessed from the full-body pose most of the time; just remember that our foot need to always make static contact with the ground (also see the SBP section of the paper) which constrains possible ankle motion. We did not revisit or change this design choice later on.

**Comment by syguan96** [comment]
Make sense. Thanks!

**Comment by jyf588** [comment]
No, we probably just took the SMPL-format output from previous works and did not exclude ankles. But honestly I think either way won't affect the statistics much since ankle is just a leaf joint.

**Comment by SlimeVRX** [comment]
I just converted the output to SMPL format

https://user-images.githubusercontent.com/99313947/232146454-75b56353-842b-4f24-bcf8-2481daceae39.mp4

**Comment by jyf588** [comment]
@SlimeVRX Nice! If you are willing to post a Github gist link here sharing with others how you did this, that would be really helpful to other researchers and practitioners.

**Comment by SlimeVRX** [comment]
Hi @jyf588 
Thanks for your work!
Here is the conversion [code](https://github.com/SlimeVRX/transformer-inertial-poser/blob/master/Hi_test/0415_SAT_SMPL.py) from Pybullet to SMPL.
I am working to compare TransPose, PIP, TIP articles with TotalCapture dataset.

**Comment by SlimeVRX** [comment]
I write a UI to control SMPL model. Code [here](https://github.com/SlimeVRX/transformer-inertial-poser/blob/master/Hi_test/0414_FRI_UI_SMPL.py)

SMPL model:

https://user-images.githubusercontent.com/99313947/232261816-abfa7123-5d02-456b-99b8-ffd5d233cf5d.mp4

Pybullet model:

https://user-images.githubusercontent.com/99313947/232261818-5e9e763a-3641-4451-bbd1-8fd2de68e121.mp4

**Comment by WingkitChou** [comment]
That's soooo cool, and i think it's really helpful for others! Thank you for your work.
