### ISSUE TITLE
question on TOTALCAPTURE

### ISSUE THREAD

**Issue by Jaceyxy** [jyf588/transformer-inertial-poser#6]
Hello, I contacted the Dip author and he sent me this file, but the file name is slightly different. I want to confirm whether the file is correct.The file the author sent me is called TotalCapture_Real_60FPS.zip.

**Comment by jyf588** [comment]
I cannot say for sure. You could try to modify this untested script of mine (viz_raw_DIP_TC.py) to see if you can visualize the files in your zip and if the visualization makes sense. (By making sense I mean I also have some code generating synthesized IMU readings for TotalCapture in this same file, and you can compare synthesized versus real to see if they very roughly match each other.)

**Comment by Jaceyxy** [comment]
Hello, I sent an e-mail to your mailbox. Could you check it?

**Comment by Jaceyxy** [comment]
@jyf588  Thanks very much!!!
