### ISSUE TITLE
fairmotion

### ISSUE THREAD

**Issue by whl-007** [jyf588/transformer-inertial-poser#9]
Hi Yifeng,
I have a question about the fairmotion.I can't execute the following sentence correctly, even though I updated pip and add domestic mirror source for it, do you know how I can solve it?
The operation I can't perform correctly:
**pip install -e .**
This is my **Error message**：
Running command git clone --filter=blob:none --quiet https://github.com/nghorbani/body_visualizer.git /tmp/pip-install-dah9q3ni/body-visualizer_a355826f8d274204be9d009b9d672c08
  error: RPC failed; curl 56 GnuTLS recv error (-110): The TLS connection was non-properly terminated.
  fatal: the remote end hung up unexpectedly
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/nghorbani/body_visualizer.git /tmp/pip-install-dah9q3ni/body-visualizer_a355826f8d274204be9d009b9d672c08 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/nghorbani/body_visualizer.git /tmp/pip-install-dah9q3ni/body-visualizer_a355826f8d274204be9d009b9d672c08 did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by jyf588** [comment]
Hi, it's hard for me to troubleshoot an installation issue on a specific computer, especially when the installation steps seem to work for many other people trying out this repo. Could it just be that access to GitHub.com is restricted, for example under the GFW of China?

**Comment by whl-007** [comment]
Sure, thank you. I will try using a VPN to download and resolve this issue.




202221040129王浩龙
***@***.***







                       
Original Email
                       
                     

Sender:"Yifeng Jiang"< ***@***.*** &gt;;

Sent Time:2023/5/30 13:46

To:"jyf588/transformer-inertial-poser"< ***@***.*** &gt;;

Cc recipient:"whl-007"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [jyf588/transformer-inertial-poser] fairmotion (Issue #9)




 
Hi, it's hard for me to troubleshoot an installation issue on a specific computer, especially when the installation steps seem to work for many other people trying out this repo. Could it just be that access to GitHub.com is restricted, for example under the GFW of China?
 
&mdash;

**Comment by whl-007** [comment]
Sure, thank you. I will try using a VPN to download and resolve this issue.

**Comment by whl-007** [comment]
我再次在windows环境下尝试，但是他报错python3.8和pickle5不兼容，您当时用的是3.8.几版本呢？

**Comment by whl-007** [comment]
Hello，I tried again in a Windows environment, but it gave an error that Python 3.8 and Pickle5 are not compatible. Which exact version of Python 3.8 did you use at that time?It was mentioned that Pickle5 can only be used with Python 3.7 or below, and that Python 3.8 and above do not support downloading the compatible Pickle5 package. However, the corresponding fairmotion version cannot be found for Python 3.7.16. Could you please provide information about your Python version?
